name: Java CI

on:
  push:
    paths:
      - 'VERSION'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

      
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    
    - name: Build with Ant
      run: ant -noinput
      
    - uses: actions/upload-artifact@v2    
      with:
        name: Jarfile
        path: build/jar/capegroup.jar